name: "Publish"

on:
  release:
    types: [ published ]

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      uses: home-assistant/builder@master
      with:
        args: |
          --all \
          --target caddy-2 \
          --docker-hub ghcr.io/caraar12345/hass-addon-caddy-2
