name: "Build and deploy HA addon"
on:
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
      packages: write
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --aarch64 --amd64 \
            --target caddy-2 \
            --docker-hub ghcr.io/${{github.repository}} \
            --image caddy-2-{arch}
      - name: Repository Dispatch
        run: |
          echo "Triggering addon update in home-assistant-addons"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/caraar12345/home-assistant-addons/dispatches \
            -f "event_type=addon_update" \
            -F "client_payload[addon]=caddy-2" \
            -F "client_payload[version]=${{ github.ref_name }}"
        env:
          GH_TOKEN: ${{ secrets.REPO_DISPATCH_PAT }}