name: "Test HA addon build"

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --aarch64 --amd64 \
          --target caddy-2 \
          --docker-hub ghcr.io/${{github.repository}} \
          --image hass-{arch}